blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/daun-gatal/chouse-ui#readme
    about: Check the README for setup and usage instructions
  - name: Discussions
    url: https://github.com/daun-gatal/chouse-ui/discussions
    about: Ask questions and share ideas in discussions
